blog/urls.py
from django.conf.urls import url

from blog.views import post_detail, post_list, manage_subscriptions

urlpatterns = [
    url(r'^(?P<post_id>\d+)/$', post_detail, name='post'),
    url(r'^subscribe/(?P<post_id>\d+)/$', manage_subscriptions, name='subscribe'),
    url(r'^$', post_list, name='index'),
]

bootstrap_calendar/urls.py
from django.conf.urls import url

from bootstrap_calendar.views import show_posts

urlpatterns = [
    url(r'^posts/', show_posts, name='posts'),
]

studio/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf.urls import i18n as i18n_urls
from rosetta import urls as rosetta_urls
from grappelli import urls as grappelli_urls
from filebrowser.sites import site
from tinymce import urls as tinymce_urls
from mce_filebrowser import urls as mce_filebrowser_urls
from account import urls as account_urls
from social.apps.django_app import urls as social_urls
from mptt_comments import urls as comments_urls
from studio.views import CustomSearchView, avatars, set_primary_avatar, delete_avatar

from blog import urls as blog_urls
from blog.feeds import BlogFeed
from blog.views import subscriptions
from bootstrap_calendar import urls as calendar_urls
from studio.views import home, SocialLoginView, flatpage
from studio.search.search import MultiIndexModelSearchForm
from studio.sitemaps import sitemaps

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^i18n/', include(i18n_urls)),
    url(r'^rosetta/', include(rosetta_urls)),
    url(r'^search/', CustomSearchView(form_class=MultiIndexModelSearchForm), name='search'),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include(grappelli_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include(tinymce_urls)),
    url(r'^mce_filebrowser/', include(mce_filebrowser_urls)),
    url(r"^account/login/$", SocialLoginView.as_view(), name="account_login"),
    url(r'^account/avatars/delete/(?P<avatar_id>\d+)$', delete_avatar, name='delete-avatar'),
    url(r'^account/avatars/primary/(?P<avatar_id>\d+)$', set_primary_avatar, name='primary-avatar'),
    url(r'^account/avatars/', avatars, name='avatars'),
    url(r'^account/subscriptions/$', subscriptions, name='subscriptions'),
    url(r'^account/', include(account_urls)),
    url(r'^social/', include(social_urls, namespace='social')),
    url(r'^mptt_comments/', include(comments_urls, namespace='comments')),
    url(r'^blog/feed/$', BlogFeed(), name='blog-feed'),
    url(r'^blog/', include(blog_urls, namespace='blog')),
    url(r'^calendar/', include(calendar_urls, namespace='calendar')),
    url(r'^$', home, name='home'),
    url(r'^(?P<url>.*/)$', flatpage),
]

if getattr(settings, 'DEBUG', None):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from datetime import datetime

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.contrib.flatpages.models import FlatPage
from tinymce.models import HTMLField

from studio.celery import app
from mptt_comments.models import MPTTComment
from mptt_comments.signals import comment_was_posted

POST_REPOST_STATUS = (
    (0, 'Do not repost'),
    (1, 'Scheduled for repost'),
    (2, 'Reposted'),
    (3, 'Failed to repost'),
)


class Tag(models.Model):
    name = models.CharField(_('Name'), max_length=255)

    class Meta:
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Author'))
    tags = models.ManyToManyField(Tag, verbose_name=_('Tags'), related_name='posts', blank=True)
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    edited = models.DateTimeField(_('Edited'), auto_now=True)
    published = models.DateTimeField(_('Published'), blank=True, null=True)
    title = models.CharField(_('Title'), max_length=255)
    text = HTMLField(_('Text'))
    is_draft = models.BooleanField(_('Draft'), default=True)
    repost_status = models.SmallIntegerField(_('Repost status'), choices=POST_REPOST_STATUS, default=1)
    repost_attempts = models.SmallIntegerField(_('Failed repost attempts'), default=0)
    repost_url = models.URLField(_('Reposted to'), blank=True, null=True)
    repost_itemid = models.PositiveIntegerField(_('Repost ID'), blank=True, null=True)

    class Meta:
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')
        ordering = ['-published', '-created', ]

    def save(self, *args, **kwargs):
        """
        Allows post publishing and republishing.
        """
        if self.is_draft:
            self.published = None
        else:
            self.published = datetime.now()
        super().save()

    def get_absolute_url(self):
        return reverse('blog:post', args=[self.id])

    def __str__(self):
        return self.title


@receiver(post_save)
def repost(sender, instance, **kwargs):
    """
    Schedule post ID for repost.
    """
    if sender is Post and instance.repost_status == 1:
        app.send_task('blog.tasks.do_repost_to_lj', [instance.id, ], countdown=5)


class PostRu(Post):
    """
    Search proxy for Post.
    """
    class Meta:
        proxy = True
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')
        ordering = ['-published', '-created', ]


class FlatPageRu(FlatPage):
    """
    Search proxy for FlatPage.
    """
    class Meta:
        proxy = True
        db_table = 'django_flatpage'
        verbose_name = _('flat page')
        verbose_name_plural = _('flat pages')
        ordering = ('url', )


class Subscription(models.Model):
    """
    Let registered users subscribe to posts to receive comments and updates by mail.
    """
    subscriber = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('User'), related_name='subscriptions')
    post = models.ForeignKey(Post, verbose_name=_('Post'), related_name='subscriptions')
    subscribed = models.DateTimeField(_('Subscribed at'), auto_now_add=True)

    class Meta:
        unique_together = ('subscriber', 'post', )
        verbose_name = _('Subscription')
        verbose_name_plural = _('Subscriptions')

    def clean_fields(self, exclude=None):
        # do not let user subscribe if his email not set
        for field in self._meta.fields:
            if field.name == 'subscriber' and not self.subscriber.email:
                raise ValidationError({
                    'subscriber': _('You must fill in your email to subscribe.'),
                })
        super().clean_fields(exclude)

    def __str__(self):
        return '<{0}>: «{1}»'.format(self.subscriber.email, self.post.title if self.post.title else 'No title')


@receiver(comment_was_posted)
def notify_subscribers(sender, comment, **kwargs):
    """
    Schedule the delivery of notifications for the subscribers.
    """
    if sender is MPTTComment:
        for subscription in comment.content_object.subscriptions.all():
            if subscription.subscriber.email:
                app.send_task('blog.tasks.do_notify_subscribers',
                              [
                                  subscription.subscriber.id,
                                  comment.id,
                              ],
                              countdown=5)

blog/views.py
import pytz
from datetime import datetime

from django.conf import settings
from django.db import IntegrityError
from django.db.models import Min, Max
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.translation import ugettext_lazy as _
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from blog.models import Post, Subscription


def get_calendar_range():
    """
    Returns calendar display range.
    """
    tz = pytz.timezone(settings.TIME_ZONE)
    result = {
        'start_date': Post.objects.filter(is_draft=False).aggregate(Min('published'))['published__min'].astimezone(tz),
        'end_date': Post.objects.filter(is_draft=False).aggregate(Max('published'))['published__max'].astimezone(tz),
    }
    return result


def post_list(request):
    """
    View list of posts.
    """
    tz = pytz.timezone(settings.TIME_ZONE)
    ctx = dict()
    query = dict(is_draft=False)
    # set calendar dates display range
    ctx.update(**get_calendar_range())
    # filter by date
    date_str = request.GET.get('date', None)
    if date_str:
        date = tz.localize(datetime.strptime(date_str, '%Y-%m-%d'))
        query['published__year'] = date.year
        query['published__month'] = date.month
        query['published__day'] = date.day
        ctx['filter_date'] = date
        ctx['current_date'] = date
    else:
        ctx['filter_date'] = None
        ctx['current_date'] = datetime.now(tz)
    # check current calendar date against range
    if ctx['current_date'] > ctx['end_date']:
        ctx['current_date'] = ctx['end_date']
    # filter by tag
    tag_str = request.GET.get('tag', None)
    if tag_str:
        query['tags__name'] = tag_str
        ctx['tag'] = tag_str
    posts_obj = Post.objects.filter(**query)
    if len(posts_obj) == 1:
        return redirect('blog:post', post_id=posts_obj[0].id)
    # paginate result
    posts_per_page = getattr(settings, 'BLOG_POSTS_PER_PAGE', 10)
    page = request.GET.get('p')
    paginator = Paginator(posts_obj, posts_per_page)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    ctx['posts'] = posts
    return render(request, template_name='blog/post_list.html', context=ctx)


def post_detail(request, post_id):
    """
    View single post.

    :param post_id: Post ID
    """
    tz = pytz.timezone(settings.TIME_ZONE)
    post = get_object_or_404(Post, id=post_id)
    ctx = {
        'post': post,
        'filter_date': post.published.astimezone(tz),
    }
    ctx.update(**get_calendar_range())
    return render(request, template_name='blog/post_detail.html', context=ctx)


@login_required
@api_view(['GET', 'POST', 'DELETE', ])
def manage_subscriptions(request, post_id):
    """
    View, create or delete a subscription to the post.

    :param post_id: the post ID.
    """
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        if request.user.email:
            subscription = Subscription(subscriber=request.user, post=post)
            try:
                subscription.save()
            except IntegrityError:
                return Response({
                    'message': _('You’re already subscribed to this object.'),
                }, status=status.HTTP_201_CREATED)
        else:
            return Response({
                'message': _('You must fill in your email to subscribe.'),
            }, status=status.HTTP_400_BAD_REQUEST)
    else:
        subscription = get_object_or_404(Subscription, subscriber=request.user, post=post)
        if request.method == 'DELETE':
            subscription.delete()
    return Response({
        'message': 'OK',
    })


@login_required
def subscriptions(request):
    ctx = {
        'subscriptions': Subscription.objects.filter(subscriber=request.user)
    }
    return render(request, template_name='account/subscriptions.html', context=ctx)

blog/templates/blog/_rss_feed.html
{% load i18n %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">{% trans 'RSS Feed' %}</h3>
                        </div>
                        <div class="panel-body">
                            <p>{% trans 'This blog' %}:
                                <a href="{% url 'blog-feed' %}">
                                    <span class="fa fa-rss pull-right rss-feed-icon"></span>
                                </a>
                            </p>
                        </div>
                    </div>

blog/templates/blog/blog_base.html
{% extends 'site_base.html' %}
{% load staticfiles i18n sitetree mathfilters %}
{% block styles %}
            <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
            <link href="{% static 'pinax/css/theme.css' %}" rel="stylesheet">
            <link href="{% static 'css/zabuto_calendar.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/bootstrap-social.css' %}" rel="stylesheet">
            <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/custom.css' %}" rel="stylesheet">
{% endblock %}
{% block scripts %}
            {% get_current_language as lang %}
            <script src="{% static 'grappelli/jquery/jquery-2.1.4.min.js' %}"></script>
            <script src="{% static 'js/bootstrap.min.js' %}"></script>
            <script src="{% static 'js/zabuto_calendar.min.js' %}"></script>
            <script>
            $(function() {
                $('#id_lang_switcher li a').click(function(e) {
                    $.post("{% url 'set_language' %}", {
                        language: $(this).attr("data-lang")
                    }, function(data, textStatus) {
                        location.reload();
                    });
                    e.preventDefault();
                });

                $('#id_calendar').zabuto_calendar({
                    language: '{{ lang }}',
                    year: {{ current_date.year }},
                    month: {{ current_date.month }},
                    show_next: {% with m=current_date.year|mul:12 %}{{ end_date.year|mul:12|add:end_date.month|sub:m|sub:current_date.month }}{% endwith %},
                    show_previous: {% with n=start_date.year|mul:12 %}{{ current_date.year|mul:12|add:current_date.month|sub:n|sub:start_date.month }}{% endwith %},
                    ajax: {
                        url: "{% url 'calendar:posts' %}"
                    },
                    action: function() {
                        if($('#' + this.id).data('hasEvent')) {
                            window.location.href = "{% url 'blog:index' %}?date=" + $('#' + this.id).data('date');
                        };
                    }
                });
            });
            </script>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/blog_base.html' %}{% load comments sitetree i18n bootstrap_pagination bleach_tags humanize %}
{% block head_title %}{{ site.name }} | {% sitetree_page_title from 'main' %}{% endblock %}
{% block body %}
            <div class="row">
                <div class="col-md-8">
                    {% sitetree_breadcrumbs from 'main' template 'sitetree_custom/breadcrumbs.html' %}
                    <h1>
                    {% if filter_date %}
                        {% trans 'Posts by' %} {{ filter_date|naturalday }}
                    {% elif tag %}
                        {% trans 'Posts by tag' %} <span class="small">&laquo;{{ tag }}&raquo;</span>
                    {% else %}
                        {% trans 'Last posts' %}
                    {% endif %}
                    </h1>
                    {% for post in posts %}
                    <div class="row">
                        <div class="col-md-12">
                            <a href="{% url 'blog:post' post.id %}">
                                <h3><i class="glyphicon glyphicon-link"></i> {{ post.title }}</h3>
                            </a>
                            <p>{% if post.published %}{{ post.published|naturaltime }}{% else %}{{ post.created|naturaltime }}{% endif %}</p>
                            {{ post.text|bleach|truncatewords:45 }}
                            <div style="clear: both"></div>
                            <p class="pull-left">
                                <a class="btn btn-default btn-sm" href="{% url 'blog:post' post.id %}#comments">
                                    <i class="glyphicon glyphicon-comment"></i>&nbsp;&nbsp;{% get_comment_count for post as comment_count %}{{ comment_count }}
                                </a>
                            </p>
                            <p class="pull-right">
                                {% for tag in post.tags.all %}
                                <span class="label label-default dog-tag">
                                    <a href="{% url 'blog:index' %}?tag={{ tag.name|iriencode }}">
                                        <i class="glyphicon glyphicon-tag"></i>&nbsp;&nbsp;{{ tag.name }}
                                    </a>
                                </span>
                                &nbsp;
                                {% endfor %}
                            </p>
                        </div>
                    </div>
                    {% if not forloop.last %}<hr />{% endif %}
                    {% endfor %}
                    {% bootstrap_paginate posts url_param_name='p' %}
                </div>
                <div class="col-md-4">
                    {% include 'search/_search.html' %}
                    {% include 'blog/_rss_feed.html' %}
                    {% include 'calendar/calendar.html' %}
                </div>
            </div>
{% endblock %}