blog/urls.py
from django.conf.urls import url

from blog.views import post_detail, post_list, manage_subscriptions

urlpatterns = [
    url(r'^(?P<post_id>\d+)/$', post_detail, name='post'),
    url(r'^subscribe/(?P<post_id>\d+)/$', manage_subscriptions, name='subscribe'),
    url(r'^$', post_list, name='index'),
]

studio/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf.urls import i18n as i18n_urls
from rosetta import urls as rosetta_urls
from grappelli import urls as grappelli_urls
from filebrowser.sites import site
from tinymce import urls as tinymce_urls
from mce_filebrowser import urls as mce_filebrowser_urls
from account import urls as account_urls
from social.apps.django_app import urls as social_urls
from mptt_comments import urls as comments_urls
from studio.views import CustomSearchView, avatars, set_primary_avatar, delete_avatar

from blog import urls as blog_urls
from blog.feeds import BlogFeed
from blog.views import subscriptions
from bootstrap_calendar import urls as calendar_urls
from studio.views import home, SocialLoginView, flatpage
from studio.search.search import MultiIndexModelSearchForm
from studio.sitemaps import sitemaps

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^i18n/', include(i18n_urls)),
    url(r'^rosetta/', include(rosetta_urls)),
    url(r'^search/', CustomSearchView(form_class=MultiIndexModelSearchForm), name='search'),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include(grappelli_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include(tinymce_urls)),
    url(r'^mce_filebrowser/', include(mce_filebrowser_urls)),
    url(r"^account/login/$", SocialLoginView.as_view(), name="account_login"),
    url(r'^account/avatars/delete/(?P<avatar_id>\d+)$', delete_avatar, name='delete-avatar'),
    url(r'^account/avatars/primary/(?P<avatar_id>\d+)$', set_primary_avatar, name='primary-avatar'),
    url(r'^account/avatars/', avatars, name='avatars'),
    url(r'^account/subscriptions/$', subscriptions, name='subscriptions'),
    url(r'^account/', include(account_urls)),
    url(r'^social/', include(social_urls, namespace='social')),
    url(r'^mptt_comments/', include(comments_urls, namespace='comments')),
    url(r'^blog/feed/$', BlogFeed(), name='blog-feed'),
    url(r'^blog/', include(blog_urls, namespace='blog')),
    url(r'^calendar/', include(calendar_urls, namespace='calendar')),
    url(r'^$', home, name='home'),
    url(r'^(?P<url>.*/)$', flatpage),
]

if getattr(settings, 'DEBUG', None):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/_account_bar.html
{% load i18n %}
{% load account_tags %}

<ul class="nav navbar-nav navbar-right">
    {% if request.user.is_authenticated %}
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                {% user_display request.user %}
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url "account_settings" %}"><i class="glyphicon glyphicon-user"></i> {% trans "Settings" %}</a></li>
                {% if request.user.is_staff %}
                    <li><a href="{% url THEME_ADMIN_URL|default:"admin:index" %}"><i class="glyphicon glyphicon-cog"></i> {% trans "Admin" %}</a></li>
                {% endif %}
                <li class="divider"></li>
                <li>
                    <a id="account_logout" href="{% url "account_logout" %}"><i class="glyphicon glyphicon-off"></i> {% trans "Log out" %}</a>
                </li>
            </ul>
        </li>
    {% else %}
        <li><a href="{% url "account_login" %}">{% trans "Log in" %}</a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li><a href="{% url "account_signup" %}">{% trans "Sign up" %}</a></li>
        {% endif %}
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url "account_logout" %}" method="POST">
    {% csrf_token %}
</form>

templates/_last_posts.html
{% load i18n bleach_tags comments humanize %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">{% trans 'Last posts' %}</h3>
                        </div>
                        <div class="panel-body">
                            {% for post in last_posts %}
                            <div class="media">
                                <div class="media-body small">
                                    <a href="{% url 'blog:post' post.id %}">
                                        <h5 class="media-heading">
                                            <i class="glyphicon glyphicon-link"></i> {{ post.title }}
                                        </h5>
                                    </a>
                                    <p class="small">{% trans 'Posted' %} {{ post.published|naturaltime }}</p>
                                    {{ post.text|bleach|truncatewords:30 }}
                                    <div style="clear: both"></div>
                                    <p class="small pull-left">
                                        <a class="btn btn-default btn-xs" href="{% url 'blog:post' post.id %}#comments">
                                            <i class="glyphicon glyphicon-comment">
                                            </i>&nbsp;{% get_comment_count for post as comment_count %}{{ comment_count }}
                                        </a>
                                    </p>
                                    <p class="small pull-right">
                                        {% for tag in post.tags.all %}
                                        <span class="label label-default dog-tag">
                                            <a href="{% url 'blog:index' %}?tag={{ tag.name|iriencode }}">
                                                <i class="glyphicon glyphicon-tag"></i>&nbsp;&nbsp;{{ tag.name }}
                                            </a>
                                        </span>
                                        &nbsp;
                                        {% endfor %}
                                    </p>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>

templates/home.html
{% extends 'site_base.html' %}{% load sitetree text_block_tags i18n %}
{% block head_title %}{{ site.name }} | {% sitetree_page_title from 'main' %}{% endblock %}
{% block body %}
            <div class="row">
                <div class="col-md-8">
                    {% sitetree_breadcrumbs from 'main' template 'sitetree_custom/breadcrumbs.html' %}
                    {% textblock 'home' %}
                </div>
                <div class="col-md-4">
                    {% include 'search/_search.html' %}
                    {% include '_last_posts.html' %}
                </div>
            </div>
{% endblock %}

templates/site_base.html
{% extends 'theme_bootstrap/base.html' %}
{% load staticfiles i18n sitetree mathfilters %}
{% block styles %}
            <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
            <link href="{% static 'pinax/css/theme.css' %}" rel="stylesheet">
            <link href="{% static 'css/awesome-bootstrap-checkbox.css' %}" rel="stylesheet">
            <link href="{% static 'css/bootstrap-social.css' %}" rel="stylesheet">
            <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/custom.css' %}" rel="stylesheet">
{% endblock %}
{% block site_brand %}
        <a class="navbar-brand" href="{% url 'home' %}">
            <i class="glyphicon glyphicon-home"></i>
        </a>
{% endblock %}
{% block nav %}
    {% sitetree_menu from 'main' include 'home' template 'sitetree/menu_bootstrap3.html' %}
    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                {% trans 'Language' %}
                <b class="caret"></b>
            </a>
            <ul id="id_lang_switcher" class="dropdown-menu">
                {% get_available_languages as languages %}
                {% get_current_language as language %}
                {% for lang in languages %}
                <li{% if lang.0 == language %} class="active"{% endif %}>
                    <a href="#" data-lang="{{ lang.0 }}">
                        {{ lang.1 }}
                    </a>
                <li>
                {% endfor %}
            </ul>
        </li>
    </ul>
{% endblock %}
{% block footer %}
            <div class="col-md-4 col-md-offset-4">
                <p style="text-align:center">&copy; Code Tinkers, 2015 adhuc.</p>
            </div>
{% endblock %}
{% block scripts %}
            {% get_current_language as lang %}
            <script src="{% static 'grappelli/jquery/jquery-2.1.4.min.js' %}"></script>
            <script src="{% static 'js/bootstrap.min.js' %}"></script>
            <script>
            $(function() {
                $('#id_lang_switcher li a').click(function(e) {
                    $.post("{% url 'set_language' %}", {
                        language: $(this).attr("data-lang")
                    }, function(data, textStatus) {
                        location.reload();
                    });
                    e.preventDefault();
                });

            });
            </script>
{% endblock %}